---
title: "Animal Crossing Example"
author: "Erin Chille"
date: "9/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load required toolkit
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(dendextend)
library(RColorBrewer)
```


Get the data
```{r}
# critic <- read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/critic.tsv', )
# user_reviews <- read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/user_reviews.tsv')
# items <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/items.csv')
villagers <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv')[,-c(1,3,6,8:11)]
head(villagers)
str(villagers)
```
Make each row a factor.
```{r}
villagers <- data.frame(lapply(villagers, as.factor), stringsAsFactors=TRUE)
str(villagers)
```

Assign factors numerical values
```{r}
villager_id <- villagers$id
villagers <- data.frame(lapply(villagers[,c(2:4)], as.numeric), stringsAsFactors = FALSE)
rownames(villagers) <- villager_id
head(villagers)
```

Try to make dendrogram. See how it turns out
```{r}
villager_dend_data <- as.matrix(villagers)

#plot(flashClust(dist(villager_dend_data), method = "average"))
#plot(hclust(dist(villager_dend_data)))
```

Customize dendrogram
```{r}
# villager_dend_data %>% 
#   dist() %>% 
#   hclust() %>% 
#   as.dendrogram() -> dend
# 
# n <- 40
# qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
# col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
# 
# pdf(file="figures/Animal_crossing_tree.pdf", height = 55, width = 30)
# dend %>%
#   set("labels_col", value = col_vector, k=40) %>%
#   #set("branches_k_color", value = col_vector, k=20) %>%
#   plot(horiz=TRUE, axes=FALSE)
# abline(v = 350, lty = 2)
# dev.off()
```

Now just do tree with personality
```{r}
villager_dend_data[,c(3)] %>% 
  dist() %>% 
  hclust() %>% 
  as.dendrogram() -> dend

#Make palaette of 8 colors with RColorBrewer
n <- 8
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

#Make dendogram pretty
pdf(file="figures/Animal_crossing_personality_tree.pdf", height = 55, width = 30)
dend %>%
  set("labels_col", value = col_vector, k=8) %>%
  plot(horiz=TRUE, axes=FALSE)
abline(v = 350, lty = 2)
dev.off()
```

